### ISSUE TITLE
all ad networks returned error

### ISSUE THREAD

**Issue by WhiteWolf-Sim** [OverShifted/GodotTapsell#10]
hi i have some question :

1.   whats diffrence between id and zone in these 2 funcs? i saw this  #5  but i didn't get it 
`func show_video_ad(id: String):`
`func request_video_ad(zone: String):` 

2. my test zone in tapsell is "638f6421150fcc4cd392bc68"
i use 
`Tapsell.request_video_ad("638f6421150fcc4cd392bc68")`
and in response of it from func  bellow , my zone changes to a random id :
`func _video_ad_request_response(zone: String, id: String):`
and the random changes every time that i use `Tapsell.request_video_ad("638f6421150fcc4cd392bc68")`

3. also when i use :
`Tapsell.show_video_ad("638f6421150fcc4cd392bc68")`
i get this error :
 "all ad networks returned error " in tapsell site it says 2 things about this error 
>1  you should update to tapsell 2.1.6 
 2   this happens when the zoneid is different with the network 
[http://docs.tapsell.ir/faq/plus-sdk/android/#%D8%AE%D8%B7%D8%A7%DB%8C-all-ad-networks-returned-error](url)

i read the the docs in this repo but can you say wahts the propper way to use the plugin cause the doc is a lil tricky  

PS : srry if my question sounds like dumb or for grammar stuff 
and also thank you for ur help and ur response

**Comment by OverShifted** [comment]
Hi.
1. Zones are things you define in the Tapsell dashboard. You can have multiple zones and use them to request an ad. When your request succeeds, an `on_video_ad_request_response` signal is triggered with a unique identifier (`id`) for the ad. Then, you can pass that identifier to the `show_video_ad` or `show_banner_ad` functions to actually show them.
2. See below:
3. You shouldn't pass your `zone` identifier to `show_video_ad` or `show_banner_ad`. Use the `id` that is passed to you from the `video_ad_request_response` signal instead.

**Comment by WhiteWolf-Sim** [comment]
thank you again
