### ISSUE TITLE
Does it work with Tapsellplus too?

### ISSUE THREAD

**Issue by 4rombusiness** [OverShifted/GodotTapsell#4]
Apparently Tapsell has been discontinued and they won't support Tapsell anymore.
Any plan to upgrade or any compatibility between this repo and Tapsellplus sdk?

**Comment by OverShifted** [comment]
I am currently working on it.
It will be published soon.

**Comment by OverShifted** [comment]
Tapsellplus and standard banner ad(#2) implementation is almost done and will be merged soon.
