### ISSUE TITLE
this plugin work for tapsellplus??  and ...

### ISSUE THREAD

**Issue by nikoosokhan** [OverShifted/GodotTapsell#5]
hi, this plugin work for tapsellplus???

and I know that "<zone id" is in  tapsellplus site but 
what is your mean (zone: String, id: String) ??

**Comment by OverShifted** [comment]
Hi Amir.
In case you are using multiple zones, you might want to use the `zone` parameter to distinguish between them in the signal handler.

**Comment by nikoosokhan** [comment]
Thank you, it helped me a lot
