### ISSUE TITLE
game crashes after export with plugin

### ISSUE THREAD

**Issue by WhiteWolf-Sim** [OverShifted/GodotTapsell#7]
hi 
exporting with custom build have no problem but when i check the plugin under the custom build after export game will crash on the device 

unfortunally the engine freezes while i try to export and after couple of minute the export will finish and won't show the gradle build window and i can't take screenshot from that window
using godot 3.5
android 7.1 
openjdk 11 
androidstudio dolphine

![Screenshot (3)](https://user-images.githubusercontent.com/91593884/206894207-1029dbc7-c6bc-4f1f-b699-8259c5216782.png)
![Screenshot (5)](https://user-images.githubusercontent.com/91593884/206894211-1f77edf8-9c31-4792-a93f-f5161d8d37dd.png)

**Comment by OverShifted** [comment]
Can you open your app's crash report on your phone?

**Comment by WhiteWolf-Sim** [comment]
> Can you open your app's crash report on your phone?

srry took a while im new in these things

here i found this from beg report fs file

`12-12 11:12:59.603  1245  1807 I am_crash: [17227,0,org.godotengine.wildballclient,982007366,java.lang.ClassNotFoundException,Didn't find class "ir.tapsell.plus.TapsellPlusInitListener" on path: DexPathList[[zip file "/data/app/org.godotengine.wildballclient-2/base.apk"],nativeLibraryDirectories=[/data/app/org.godotengine.wildballclient-2/lib/arm64, /data/app/org.godotengine.wildballclient-2/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64, /system/vendor/lib64, /product/lib64]],BaseDexClassLoader.java,56]
12-12 11:12:59.626  1245  1807 I am_finish_activity: [0,8817607,21,org.godotengine.wildballclient/com.godot.game.GodotApp,force-crash]`



`12-12 11:12:59.581 17227 17247 E AndroidRuntime: FATAL EXCEPTION: GLThread 1919
12-12 11:12:59.581 17227 17247 E AndroidRuntime: Process: org.godotengine.wildballclient, PID: 17227
12-12 11:12:59.581 17227 17247 E AndroidRuntime: java.lang.NoClassDefFoundError: Failed resolution of: Lir/tapsell/plus/TapsellPlusInitListener;
12-12 11:12:59.581 17227 17247 E AndroidRuntime: 	at java.lang.Class.classForName(Native Method)
12-12 11:12:59.581 17227 17247 E AndroidRuntime: 	at java.lang.Class.forName(Class.java:400)
12-12 11:12:59.581 17227 17247 E AndroidRuntime: 	at java.lang.Class.forName(Class.java:326)
12-12 11:12:59.581 17227 17247 E AndroidRuntime: 	at org.godotengine.godot.plugin.GodotPluginRegistry.loadPlugins(GodotPluginRegistry.java:140)
12-12 11:12:59.581 17227 17247 E AndroidRuntime: 	at org.godotengine.godot.plugin.GodotPluginRegistry.<init>(GodotPluginRegistry.java:62)
12-12 11:12:59.581 17227 17247 E AndroidRuntime: 	at org.godotengine.godot.plugin.GodotPluginRegistry.initializePluginRegistry(GodotPluginRegistry.java:94)
12-12 11:12:59.581 17227 17247 E AndroidRuntime: 	at org.godotengine.godot.Godot.onCreate(Godot.java:608)
12-12 11:12:59.581 17227 17247 E AndroidRuntime: 	at androidx.fragment.app.Fragment.performCreate(Fragment.java:2949)
12-12 11:12:59.581 17227 17247 E AndroidRuntime: 	at androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:475)
12-12 11:12:59.581 17227 17247 E AndroidRuntime: 	at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:278)
12-12 11:12:59.581 17227 17247 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:2189)
12-12 11:12:59.581 17227 17247 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:2100)
12-12 11:12:59.581 17227 17247 E AndroidRuntime: 	at androidx.fragment.app.FragmentManager.execSingleAction(FragmentManager.java:1971)
12-12 11:12:59.581 17227 17247 E AndroidRuntime: 	at androidx.fragment.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:311)
12-12 11:12:59.581 17227 17247 E AndroidRuntime: 	at org.godotengine.godot.FullScreenGodotApp.onCreate(FullScreenGodotApp.java:69)
12-12 11:12:59.581 17227 17247 E AndroidRuntime: 	at com.godot.game.GodotApp.onCreate(GodotApp.java:45)
12-12 11:12:59.581 17227 17247 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:6915)
12-12 11:12:59.581 17227 17247 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1123)
12-12 11:12:59.581 17227 17247 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2746)
12-12 11:12:59.581 17227 17247 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2864)
12-12 11:12:59.581 17227 17247 E AndroidRuntime: 	at android.app.ActivityThread.-wrap12(ActivityThread.java)
12-12 11:12:59.581 17227 17247 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1567)
12-12 11:12:59.581 17227 17247 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:105)
12-12 11:12:59.581 17227 17247 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:156)
12-12 11:12:59.581 17227 17247 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6517)
12-12 11:12:59.581 17227 17247 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
12-12 11:12:59.581 17227 17247 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
12-12 11:12:59.581 17227 17247 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)
12-12 11:12:59.581 17227 17247 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "ir.tapsell.plus.TapsellPlusInitListener" on path: DexPathList[[zip file "/data/app/org.godotengine.wildballclient-2/base.apk"],nativeLibraryDirectories=[/data/app/org.godotengine.wildballclient-2/lib/arm64, /data/app/org.godotengine.wildballclient-2/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64, /system/vendor/lib64, /product/lib64]]
12-12 11:12:59.581 17227 17247 E AndroidRuntime: 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
12-12 11:12:59.581 17227 17247 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
12-12 11:12:59.581 17227 17247 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
12-12 11:12:59.581 17227 17247 E AndroidRuntime: 	... 28 more`

**Comment by OverShifted** [comment]
What's in your projects's `res://android/plugins` directory?

**Comment by WhiteWolf-Sim** [comment]
> What's in your projects's `res://android/plugins` directory?

GodotTapsell.gdap
GodotTapsell-release.aar

i downloaded them from the release page of the repo

**Comment by OverShifted** [comment]
My fault. `GodotTapsell.gdap` had the older version of Tapsell SDK as its dependency. 
I replaced it with the newer version.
Just update your `GodotTapsell.gdap` file and it should fix your issue.

**Comment by WhiteWolf-Sim** [comment]
> My fault. `GodotTapsell.gdap` had the older version of Tapsell SDK as its dependency. I replaced it with the newer version. Just update your `GodotTapsell.gdap` file and it should fix your issue.



thank you 👍
