### ISSUE TITLE
export aar

### ISSUE THREAD

**Issue by reza-n1** [OverShifted/GodotTapsell#8]
سلام وقت شما بخیر 

![how aar](https://user-images.githubusercontent.com/120559258/207574996-d2685e14-be77-4de2-8b0c-3a856c052c1a.PNG)

یه سری تغییرات روی فایل java دادم چطوری میشه خروجی aar گرفت؟؟

**Comment by OverShifted** [comment]
سلام.
بعد از بیلد کردن پروژه، می‌تونید فایل `aar` رو داخل پوشه‌ی `AndroidStudioProject/GodotTapsell/GodotTapsell/build/outputs/aar` پیدا کنید.
