### ISSUE TITLE
export aar

### ISSUE THREAD

**Issue by nikoosokhan** [OverShifted/GodotTapsell#9]
سلام 
زمانی که بیلد میگیرم این ارور رو میده. ممنون میشم راهنماییم کنید

![err](https://user-images.githubusercontent.com/39468344/207712094-15b8fe7a-31f1-49c5-9662-da630ce5296e.jpg)

**Comment by OverShifted** [comment]
سلام.
لطفاً قبل باز کردن ایشیو، مشکل خود را در اینترنت جستجو کنید.
https://docs.godotengine.org/en/stable/tutorials/platform/android/android_plugin.html#android-plugin
